id: I06E26E65
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:48:08+00:00'
last_modified: '2022-06-08T05:33:33.169229+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3375
  title: སུམ་ཅུ་པའི་རྣམ་བཤད་ཀུན་བཟང་དགོངས་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F423:
      image_group_id: I3CN3529
      title: ''
      total_pages: 136
      order: 1
      base_file: F423.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
