id: I06E26E65
legacy_id: P006602
ocr_import_info:
  bdrc_scan_id: W3CN3375
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T15:47:16'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:28:30.893260+00:00'
last_modified: 2022-08-27 19:28:41.632320
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3375
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3375
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སུམ་ཅུ་པའི་རྣམ་བཤད་ཀུན་བཟང་དགོངས་རྒྱན།
  author: པྲ་ཏི་དགེ་བཤེས་རིན་ཆེན་དོན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9767546291365645
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I3CN3529:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3529
      total_pages: 136
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN3529.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9767546291365645
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
